-- 200 Unique Questions Seed Data
INSERT INTO public.question_bank (question_text, options, correct_option, topic, difficulty)
VALUES
('What is the next number in the arithmetic progression: 1, 4, 7, 10?', '["11", "14", "13", "12"]'::jsonb, 2, 'Year 1 - Aptitude', 'easy'),
('What is the next number in the arithmetic progression: 2, 5, 8, 11?', '["12", "14", "15", "13"]'::jsonb, 1, 'Year 1 - Aptitude', 'easy'),
('What is the next number in the arithmetic progression: 3, 6, 9, 12?', '["13", "14", "15", "16"]'::jsonb, 2, 'Year 1 - Aptitude', 'easy'),
('What is the next number in the arithmetic progression: 4, 7, 10, 13?', '["15", "17", "14", "16"]'::jsonb, 3, 'Year 1 - Aptitude', 'easy'),
('What is the next number in the arithmetic progression: 5, 8, 11, 14?', '["16", "15", "17", "18"]'::jsonb, 2, 'Year 1 - Aptitude', 'easy'),
('What is the next number in the arithmetic progression: 6, 9, 12, 15?', '["18", "17", "16", "19"]'::jsonb, 0, 'Year 1 - Aptitude', 'easy'),
('What is the next number in the arithmetic progression: 7, 10, 13, 16?', '["17", "18", "19", "20"]'::jsonb, 2, 'Year 1 - Aptitude', 'easy'),
('What is the next number in the arithmetic progression: 8, 11, 14, 17?', '["21", "18", "19", "20"]'::jsonb, 3, 'Year 1 - Aptitude', 'easy'),
('What is the next number in the arithmetic progression: 9, 12, 15, 18?', '["21", "20", "19", "22"]'::jsonb, 0, 'Year 1 - Aptitude', 'easy'),
('What is the next number in the arithmetic progression: 10, 13, 16, 19?', '["23", "22", "20", "21"]'::jsonb, 1, 'Year 1 - Aptitude', 'easy'),
('What is 5% of 50?', '["7", "-3", "12", "2"]'::jsonb, 3, 'Year 1 - Aptitude', 'medium'),
('What is 10% of 100?', '["20", "5", "10", "15"]'::jsonb, 2, 'Year 1 - Aptitude', 'medium'),
('What is 15% of 150?', '["22", "32", "27", "17"]'::jsonb, 0, 'Year 1 - Aptitude', 'medium'),
('What is 20% of 200?', '["45", "50", "40", "35"]'::jsonb, 2, 'Year 1 - Aptitude', 'medium'),
('What is 25% of 250?', '["67", "57", "62", "72"]'::jsonb, 2, 'Year 1 - Aptitude', 'medium'),
('What is 30% of 300?', '["90", "100", "85", "95"]'::jsonb, 0, 'Year 1 - Aptitude', 'medium'),
('What is 35% of 350?', '["117", "122", "127", "132"]'::jsonb, 1, 'Year 1 - Aptitude', 'medium'),
('What is 40% of 400?', '["170", "160", "155", "165"]'::jsonb, 1, 'Year 1 - Aptitude', 'medium'),
('What is 45% of 450?', '["207", "212", "202", "197"]'::jsonb, 2, 'Year 1 - Aptitude', 'medium'),
('What is 50% of 500?', '["250", "245", "260", "255"]'::jsonb, 0, 'Year 1 - Aptitude', 'medium'),
('What is 55% of 550?', '["307", "312", "297", "302"]'::jsonb, 3, 'Year 1 - Aptitude', 'medium'),
('What is 60% of 600?', '["365", "370", "360", "355"]'::jsonb, 2, 'Year 1 - Aptitude', 'medium'),
('If Alice can complete a task in 2 days and Bob can complete it in 4 days, how many days will it take them together?', '["1.33", "0.33000000000000007", "3.33", "2.33"]'::jsonb, 0, 'Year 1 - Aptitude', 'medium'),
('If Alice can complete a task in 3 days and Bob can complete it in 6 days, how many days will it take them together?', '["4.0", "1.0", "2.0", "3.0"]'::jsonb, 2, 'Year 1 - Aptitude', 'medium'),
('If Alice can complete a task in 4 days and Bob can complete it in 8 days, how many days will it take them together?', '["2.67", "3.67", "4.67", "1.67"]'::jsonb, 0, 'Year 1 - Aptitude', 'medium'),
('If Alice can complete a task in 5 days and Bob can complete it in 10 days, how many days will it take them together?', '["5.33", "3.33", "2.33", "4.33"]'::jsonb, 1, 'Year 1 - Aptitude', 'medium'),
('If Alice can complete a task in 6 days and Bob can complete it in 12 days, how many days will it take them together?', '["5.0", "3.0", "6.0", "4.0"]'::jsonb, 3, 'Year 1 - Aptitude', 'medium'),
('If Alice can complete a task in 7 days and Bob can complete it in 14 days, how many days will it take them together?', '["4.67", "3.67", "5.67", "6.67"]'::jsonb, 0, 'Year 1 - Aptitude', 'medium'),
('If Alice can complete a task in 8 days and Bob can complete it in 16 days, how many days will it take them together?', '["6.33", "7.33", "4.33", "5.33"]'::jsonb, 3, 'Year 1 - Aptitude', 'medium'),
('If Alice can complete a task in 9 days and Bob can complete it in 18 days, how many days will it take them together?', '["8.0", "7.0", "5.0", "6.0"]'::jsonb, 3, 'Year 1 - Aptitude', 'medium'),
('If Alice can complete a task in 10 days and Bob can complete it in 20 days, how many days will it take them together?', '["5.67", "7.67", "8.67", "6.67"]'::jsonb, 3, 'Year 1 - Aptitude', 'medium'),
('If Alice can complete a task in 11 days and Bob can complete it in 22 days, how many days will it take them together?', '["8.33", "9.33", "7.33", "6.33"]'::jsonb, 2, 'Year 1 - Aptitude', 'medium'),
('If Alice can complete a task in 12 days and Bob can complete it in 24 days, how many days will it take them together?', '["7.0", "9.0", "8.0", "10.0"]'::jsonb, 2, 'Year 1 - Aptitude', 'medium'),
('If Alice can complete a task in 13 days and Bob can complete it in 26 days, how many days will it take them together?', '["9.67", "7.67", "8.67", "10.67"]'::jsonb, 2, 'Year 1 - Aptitude', 'medium'),
('Which component of an OS is primarily responsible for process management?', '["Shell", "Compiler", "Kernel", "Loader"]'::jsonb, 2, 'Year 1 - Core CS', 'easy'),
('Which component of an OS is primarily responsible for memory management?', '["Loader", "Compiler", "Shell", "Kernel"]'::jsonb, 3, 'Year 1 - Core CS', 'easy'),
('Which component of an OS is primarily responsible for file systems?', '["Compiler", "Shell", "Loader", "Kernel"]'::jsonb, 3, 'Year 1 - Core CS', 'easy'),
('Which component of an OS is primarily responsible for device drivers?', '["Kernel", "Shell", "Compiler", "Loader"]'::jsonb, 0, 'Year 1 - Core CS', 'easy'),
('Which component of an OS is primarily responsible for interrupts?', '["Loader", "Shell", "Kernel", "Compiler"]'::jsonb, 2, 'Year 1 - Core CS', 'easy'),
('Which component of an OS is primarily responsible for process management?', '["Compiler", "Kernel", "Loader", "Shell"]'::jsonb, 1, 'Year 1 - Core CS', 'easy'),
('Which component of an OS is primarily responsible for memory management?', '["Shell", "Kernel", "Compiler", "Loader"]'::jsonb, 1, 'Year 1 - Core CS', 'easy'),
('Which component of an OS is primarily responsible for file systems?', '["Kernel", "Loader", "Compiler", "Shell"]'::jsonb, 0, 'Year 1 - Core CS', 'easy'),
('Which component of an OS is primarily responsible for device drivers?', '["Kernel", "Shell", "Loader", "Compiler"]'::jsonb, 0, 'Year 1 - Core CS', 'easy'),
('Which component of an OS is primarily responsible for interrupts?', '["Loader", "Kernel", "Compiler", "Shell"]'::jsonb, 1, 'Year 1 - Core CS', 'easy'),
('Which protocol is typically used for HTTP communications?', '["ARP", "HTTP", "IP", "ICMP"]'::jsonb, 1, 'Year 1 - Core CS', 'easy'),
('Which protocol is typically used for FTP communications?', '["ARP", "IP", "FTP", "ICMP"]'::jsonb, 2, 'Year 1 - Core CS', 'easy'),
('Which protocol is typically used for SMTP communications?', '["IP", "ARP", "SMTP", "ICMP"]'::jsonb, 2, 'Year 1 - Core CS', 'easy'),
('Which protocol is typically used for TCP communications?', '["IP", "ICMP", "TCP", "ARP"]'::jsonb, 2, 'Year 1 - Core CS', 'easy'),
('Which protocol is typically used for UDP communications?', '["ICMP", "ARP", "UDP", "IP"]'::jsonb, 2, 'Year 1 - Core CS', 'easy'),
('Which protocol is typically used for HTTP communications?', '["ICMP", "ARP", "HTTP", "IP"]'::jsonb, 2, 'Year 1 - Core CS', 'easy'),
('Which protocol is typically used for FTP communications?', '["FTP", "ICMP", "ARP", "IP"]'::jsonb, 0, 'Year 1 - Core CS', 'easy'),
('Which protocol is typically used for SMTP communications?', '["SMTP", "ICMP", "IP", "ARP"]'::jsonb, 0, 'Year 1 - Core CS', 'easy'),
('Which protocol is typically used for TCP communications?', '["ARP", "IP", "ICMP", "TCP"]'::jsonb, 3, 'Year 1 - Core CS', 'easy'),
('Which protocol is typically used for UDP communications?', '["IP", "ARP", "ICMP", "UDP"]'::jsonb, 3, 'Year 1 - Core CS', 'easy'),
('In a relational database, what is the primary purpose of a Primary Key?', '["To delete data", "To enforce primary key rules", "To speed up queries", "To store data"]'::jsonb, 1, 'Year 1 - Core CS', 'medium'),
('In a relational database, what is the primary purpose of a Foreign Key?', '["To enforce foreign key rules", "To speed up queries", "To delete data", "To store data"]'::jsonb, 0, 'Year 1 - Core CS', 'medium'),
('In a relational database, what is the primary purpose of a Index?', '["To enforce index rules", "To delete data", "To store data", "To speed up queries"]'::jsonb, 0, 'Year 1 - Core CS', 'medium'),
('In a relational database, what is the primary purpose of a View?', '["To speed up queries", "To delete data", "To enforce view rules", "To store data"]'::jsonb, 2, 'Year 1 - Core CS', 'medium'),
('In a relational database, what is the primary purpose of a Trigger?', '["To delete data", "To speed up queries", "To enforce trigger rules", "To store data"]'::jsonb, 2, 'Year 1 - Core CS', 'medium'),
('In a relational database, what is the primary purpose of a Primary Key?', '["To store data", "To speed up queries", "To delete data", "To enforce primary key rules"]'::jsonb, 3, 'Year 1 - Core CS', 'medium'),
('In a relational database, what is the primary purpose of a Foreign Key?', '["To speed up queries", "To delete data", "To store data", "To enforce foreign key rules"]'::jsonb, 3, 'Year 1 - Core CS', 'medium'),
('In a relational database, what is the primary purpose of a Index?', '["To store data", "To delete data", "To enforce index rules", "To speed up queries"]'::jsonb, 2, 'Year 1 - Core CS', 'medium'),
('In a relational database, what is the primary purpose of a View?', '["To delete data", "To store data", "To speed up queries", "To enforce view rules"]'::jsonb, 3, 'Year 1 - Core CS', 'medium'),
('In a relational database, what is the primary purpose of a Trigger?', '["To store data", "To delete data", "To enforce trigger rules", "To speed up queries"]'::jsonb, 2, 'Year 1 - Core CS', 'medium'),
('In a relational database, what is the primary purpose of a Primary Key?', '["To store data", "To delete data", "To enforce primary key rules", "To speed up queries"]'::jsonb, 2, 'Year 1 - Core CS', 'medium'),
('In a relational database, what is the primary purpose of a Foreign Key?', '["To enforce foreign key rules", "To delete data", "To speed up queries", "To store data"]'::jsonb, 0, 'Year 1 - Core CS', 'medium'),
('In a relational database, what is the primary purpose of a Index?', '["To enforce index rules", "To delete data", "To speed up queries", "To store data"]'::jsonb, 0, 'Year 1 - Core CS', 'medium'),
('In C programming, what is the size of ''int'' in a standard 32-bit compiler?', '["4 bytes", "2 bytes", "4 bytes", "1 byte"]'::jsonb, 0, 'Year 1 - Programming', 'easy'),
('In C programming, what is the size of ''float'' in a standard 32-bit compiler?', '["2 bytes", "4 bytes", "1 byte", "4 bytes"]'::jsonb, 1, 'Year 1 - Programming', 'easy'),
('In C programming, what is the size of ''char'' in a standard 32-bit compiler?', '["4 bytes", "1 byte", "1 byte", "2 bytes"]'::jsonb, 1, 'Year 1 - Programming', 'easy'),
('In C programming, what is the size of ''double'' in a standard 32-bit compiler?', '["2 bytes", "4 bytes", "1 byte", "8 bytes"]'::jsonb, 3, 'Year 1 - Programming', 'easy'),
('In C programming, what is the size of ''void'' in a standard 32-bit compiler?', '["1 byte", "0 bytes", "4 bytes", "2 bytes"]'::jsonb, 1, 'Year 1 - Programming', 'easy'),
('In C programming, what is the size of ''int'' in a standard 32-bit compiler?', '["4 bytes", "1 byte", "2 bytes", "4 bytes"]'::jsonb, 0, 'Year 1 - Programming', 'easy'),
('In C programming, what is the size of ''float'' in a standard 32-bit compiler?', '["2 bytes", "4 bytes", "4 bytes", "1 byte"]'::jsonb, 1, 'Year 1 - Programming', 'easy'),
('In C programming, what is the size of ''char'' in a standard 32-bit compiler?', '["2 bytes", "1 byte", "1 byte", "4 bytes"]'::jsonb, 1, 'Year 1 - Programming', 'easy'),
('In C programming, what is the size of ''double'' in a standard 32-bit compiler?', '["2 bytes", "4 bytes", "1 byte", "8 bytes"]'::jsonb, 3, 'Year 1 - Programming', 'easy'),
('In C programming, what is the size of ''void'' in a standard 32-bit compiler?', '["0 bytes", "2 bytes", "1 byte", "4 bytes"]'::jsonb, 0, 'Year 1 - Programming', 'easy'),
('In C programming, what is the size of ''int'' in a standard 32-bit compiler?', '["4 bytes", "2 bytes", "4 bytes", "1 byte"]'::jsonb, 0, 'Year 1 - Programming', 'easy'),
('What is the output of ''printf("%d", 0 + 0);'' in C?', '["0", "0", "Compilation Error", "0"]'::jsonb, 0, 'Year 1 - Programming', 'medium'),
('What is the output of ''printf("%d", 1 + 2);'' in C?', '["1", "2", "Compilation Error", "3"]'::jsonb, 3, 'Year 1 - Programming', 'medium'),
('What is the output of ''printf("%d", 2 + 4);'' in C?', '["6", "2", "4", "Compilation Error"]'::jsonb, 0, 'Year 1 - Programming', 'medium'),
('What is the output of ''printf("%d", 3 + 6);'' in C?', '["9", "Compilation Error", "6", "3"]'::jsonb, 0, 'Year 1 - Programming', 'medium'),
('What is the output of ''printf("%d", 4 + 8);'' in C?', '["4", "8", "12", "Compilation Error"]'::jsonb, 2, 'Year 1 - Programming', 'medium'),
('What is the output of ''printf("%d", 5 + 10);'' in C?', '["5", "15", "10", "Compilation Error"]'::jsonb, 1, 'Year 1 - Programming', 'medium'),
('What is the output of ''printf("%d", 6 + 12);'' in C?', '["18", "12", "Compilation Error", "6"]'::jsonb, 0, 'Year 1 - Programming', 'medium'),
('What is the output of ''printf("%d", 7 + 14);'' in C?', '["7", "21", "Compilation Error", "14"]'::jsonb, 1, 'Year 1 - Programming', 'medium'),
('What is the output of ''printf("%d", 8 + 16);'' in C?', '["24", "16", "Compilation Error", "8"]'::jsonb, 0, 'Year 1 - Programming', 'medium'),
('What is the output of ''printf("%d", 9 + 18);'' in C?', '["18", "Compilation Error", "27", "9"]'::jsonb, 2, 'Year 1 - Programming', 'medium'),
('What is the output of ''printf("%d", 10 + 20);'' in C?', '["20", "30", "Compilation Error", "10"]'::jsonb, 1, 'Year 1 - Programming', 'medium'),
('Which operator is used for logical AND in C? (Variant 0)', '["||", "&&", "!", "&"]'::jsonb, 1, 'Year 1 - Programming', 'easy'),
('Which operator is used for logical AND in C? (Variant 1)', '["||", "&&", "!", "&"]'::jsonb, 1, 'Year 1 - Programming', 'easy'),
('Which operator is used for logical AND in C? (Variant 2)', '["&&", "!", "&", "||"]'::jsonb, 0, 'Year 1 - Programming', 'easy'),
('Which operator is used for logical AND in C? (Variant 3)', '["!", "&&", "&", "||"]'::jsonb, 1, 'Year 1 - Programming', 'easy'),
('Which operator is used for logical AND in C? (Variant 4)', '["&&", "!", "||", "&"]'::jsonb, 0, 'Year 1 - Programming', 'easy'),
('Which operator is used for logical AND in C? (Variant 5)', '["!", "||", "&&", "&"]'::jsonb, 2, 'Year 1 - Programming', 'easy'),
('Which operator is used for logical AND in C? (Variant 6)', '["||", "&&", "!", "&"]'::jsonb, 1, 'Year 1 - Programming', 'easy'),
('Which operator is used for logical AND in C? (Variant 7)', '["!", "&", "&&", "||"]'::jsonb, 2, 'Year 1 - Programming', 'easy'),
('Which operator is used for logical AND in C? (Variant 8)', '["&&", "||", "!", "&"]'::jsonb, 0, 'Year 1 - Programming', 'easy'),
('Which operator is used for logical AND in C? (Variant 9)', '["||", "&&", "!", "&"]'::jsonb, 1, 'Year 1 - Programming', 'easy'),
('Which operator is used for logical AND in C? (Variant 10)', '["!", "||", "&&", "&"]'::jsonb, 2, 'Year 1 - Programming', 'easy'),
('What is the worst-case time complexity for insertion in a AVL Tree?', '["O(n log n)", "O(1)", "O(log n)", "O(n)"]'::jsonb, 2, 'Year 2 - Advanced DSA', 'hard'),
('What is the worst-case time complexity for insertion in a Red-Black Tree?', '["O(n)", "O(n log n)", "O(log n)", "O(1)"]'::jsonb, 2, 'Year 2 - Advanced DSA', 'hard'),
('What is the worst-case time complexity for insertion in a B-Tree?', '["O(n)", "O(n log n)", "O(1)", "O(log n)"]'::jsonb, 3, 'Year 2 - Advanced DSA', 'hard'),
('What is the worst-case time complexity for insertion in a Trie?', '["O(n)", "O(1)", "O(log n)", "O(n log n)"]'::jsonb, 0, 'Year 2 - Advanced DSA', 'hard'),
('What is the worst-case time complexity for insertion in a Graph?', '["O(n log n)", "O(n)", "O(1)", "O(log n)"]'::jsonb, 1, 'Year 2 - Advanced DSA', 'hard'),
('What is the worst-case time complexity for insertion in a AVL Tree?', '["O(n)", "O(n log n)", "O(log n)", "O(1)"]'::jsonb, 2, 'Year 2 - Advanced DSA', 'hard'),
('What is the worst-case time complexity for insertion in a Red-Black Tree?', '["O(log n)", "O(1)", "O(n)", "O(n log n)"]'::jsonb, 0, 'Year 2 - Advanced DSA', 'hard'),
('What is the worst-case time complexity for insertion in a B-Tree?', '["O(n log n)", "O(log n)", "O(n)", "O(1)"]'::jsonb, 1, 'Year 2 - Advanced DSA', 'hard'),
('What is the worst-case time complexity for insertion in a Trie?', '["O(n)", "O(1)", "O(n log n)", "O(log n)"]'::jsonb, 0, 'Year 2 - Advanced DSA', 'hard'),
('What is the worst-case time complexity for insertion in a Graph?', '["O(n)", "O(n log n)", "O(1)", "O(log n)"]'::jsonb, 0, 'Year 2 - Advanced DSA', 'hard'),
('What is the worst-case time complexity for insertion in a AVL Tree?', '["O(log n)", "O(n log n)", "O(1)", "O(n)"]'::jsonb, 0, 'Year 2 - Advanced DSA', 'hard'),
('What is the worst-case time complexity for insertion in a Red-Black Tree?', '["O(1)", "O(n)", "O(log n)", "O(n log n)"]'::jsonb, 2, 'Year 2 - Advanced DSA', 'hard'),
('Which algorithm is best suited to find the shortest path in a graph with negative weights? (Case 0)', '["Dijkstra", "Bellman-Ford", "BFS", "DFS"]'::jsonb, 1, 'Year 2 - Advanced DSA', 'medium'),
('Which algorithm is best suited to find the shortest path in a graph with negative weights? (Case 1)', '["Dijkstra", "BFS", "DFS", "Bellman-Ford"]'::jsonb, 3, 'Year 2 - Advanced DSA', 'medium'),
('Which algorithm is best suited to find the shortest path in a graph with negative weights? (Case 2)', '["Bellman-Ford", "Dijkstra", "BFS", "DFS"]'::jsonb, 0, 'Year 2 - Advanced DSA', 'medium'),
('Which algorithm is best suited to find the shortest path in a graph with negative weights? (Case 3)', '["DFS", "Bellman-Ford", "Dijkstra", "BFS"]'::jsonb, 1, 'Year 2 - Advanced DSA', 'medium'),
('Which algorithm is best suited to find the shortest path in a graph with negative weights? (Case 4)', '["Dijkstra", "Bellman-Ford", "DFS", "BFS"]'::jsonb, 1, 'Year 2 - Advanced DSA', 'medium'),
('Which algorithm is best suited to find the shortest path in a graph with negative weights? (Case 5)', '["DFS", "Dijkstra", "BFS", "Bellman-Ford"]'::jsonb, 3, 'Year 2 - Advanced DSA', 'medium'),
('Which algorithm is best suited to find the shortest path in a graph with negative weights? (Case 6)', '["Dijkstra", "BFS", "DFS", "Bellman-Ford"]'::jsonb, 3, 'Year 2 - Advanced DSA', 'medium'),
('Which algorithm is best suited to find the shortest path in a graph with negative weights? (Case 7)', '["Bellman-Ford", "DFS", "Dijkstra", "BFS"]'::jsonb, 0, 'Year 2 - Advanced DSA', 'medium'),
('Which algorithm is best suited to find the shortest path in a graph with negative weights? (Case 8)', '["DFS", "Dijkstra", "BFS", "Bellman-Ford"]'::jsonb, 3, 'Year 2 - Advanced DSA', 'medium'),
('Which algorithm is best suited to find the shortest path in a graph with negative weights? (Case 9)', '["Dijkstra", "DFS", "Bellman-Ford", "BFS"]'::jsonb, 2, 'Year 2 - Advanced DSA', 'medium'),
('Which algorithm is best suited to find the shortest path in a graph with negative weights? (Case 10)', '["BFS", "Dijkstra", "Bellman-Ford", "DFS"]'::jsonb, 2, 'Year 2 - Advanced DSA', 'medium'),
('In dynamic programming, what is the time complexity of solving the 0/1 Knapsack problem with capacity W and n items? (Variation 0)', '["O(2^n)", "O(n*W)", "O(n)", "O(W)"]'::jsonb, 1, 'Year 2 - Advanced DSA', 'hard'),
('In dynamic programming, what is the time complexity of solving the 0/1 Knapsack problem with capacity W and n items? (Variation 1)', '["O(2^n)", "O(n*W)", "O(n)", "O(W)"]'::jsonb, 1, 'Year 2 - Advanced DSA', 'hard'),
('In dynamic programming, what is the time complexity of solving the 0/1 Knapsack problem with capacity W and n items? (Variation 2)', '["O(n*W)", "O(n)", "O(W)", "O(2^n)"]'::jsonb, 0, 'Year 2 - Advanced DSA', 'hard'),
('In dynamic programming, what is the time complexity of solving the 0/1 Knapsack problem with capacity W and n items? (Variation 3)', '["O(W)", "O(2^n)", "O(n*W)", "O(n)"]'::jsonb, 2, 'Year 2 - Advanced DSA', 'hard'),
('In dynamic programming, what is the time complexity of solving the 0/1 Knapsack problem with capacity W and n items? (Variation 4)', '["O(2^n)", "O(n)", "O(W)", "O(n*W)"]'::jsonb, 3, 'Year 2 - Advanced DSA', 'hard'),
('In dynamic programming, what is the time complexity of solving the 0/1 Knapsack problem with capacity W and n items? (Variation 5)', '["O(2^n)", "O(n*W)", "O(n)", "O(W)"]'::jsonb, 1, 'Year 2 - Advanced DSA', 'hard'),
('In dynamic programming, what is the time complexity of solving the 0/1 Knapsack problem with capacity W and n items? (Variation 6)', '["O(n)", "O(2^n)", "O(W)", "O(n*W)"]'::jsonb, 3, 'Year 2 - Advanced DSA', 'hard'),
('In dynamic programming, what is the time complexity of solving the 0/1 Knapsack problem with capacity W and n items? (Variation 7)', '["O(W)", "O(n*W)", "O(2^n)", "O(n)"]'::jsonb, 1, 'Year 2 - Advanced DSA', 'hard'),
('In dynamic programming, what is the time complexity of solving the 0/1 Knapsack problem with capacity W and n items? (Variation 8)', '["O(W)", "O(n)", "O(2^n)", "O(n*W)"]'::jsonb, 3, 'Year 2 - Advanced DSA', 'hard'),
('In dynamic programming, what is the time complexity of solving the 0/1 Knapsack problem with capacity W and n items? (Variation 9)', '["O(2^n)", "O(n)", "O(W)", "O(n*W)"]'::jsonb, 3, 'Year 2 - Advanced DSA', 'hard'),
('In dynamic programming, what is the time complexity of solving the 0/1 Knapsack problem with capacity W and n items? (Variation 10)', '["O(W)", "O(n)", "O(n*W)", "O(2^n)"]'::jsonb, 2, 'Year 2 - Advanced DSA', 'hard'),
('In a distributed system, what is the main role of a Load Balancer?', '["Distribute traffic", "Render UI", "Store persistent data", "Compile code"]'::jsonb, 0, 'Year 2 - System Design', 'medium'),
('In a distributed system, what is the main role of a API Gateway?', '["Distribute traffic", "Store persistent data", "Compile code", "Render UI"]'::jsonb, 0, 'Year 2 - System Design', 'medium'),
('In a distributed system, what is the main role of a Cache?', '["Distribute traffic", "Store persistent data", "Compile code", "Render UI"]'::jsonb, 0, 'Year 2 - System Design', 'medium'),
('In a distributed system, what is the main role of a Message Queue?', '["Distribute traffic", "Render UI", "Store persistent data", "Compile code"]'::jsonb, 0, 'Year 2 - System Design', 'medium'),
('In a distributed system, what is the main role of a Database Index?', '["Store persistent data", "Distribute traffic", "Compile code", "Render UI"]'::jsonb, 1, 'Year 2 - System Design', 'medium'),
('In a distributed system, what is the main role of a Load Balancer?', '["Distribute traffic", "Compile code", "Render UI", "Store persistent data"]'::jsonb, 0, 'Year 2 - System Design', 'medium'),
('In a distributed system, what is the main role of a API Gateway?', '["Distribute traffic", "Store persistent data", "Compile code", "Render UI"]'::jsonb, 0, 'Year 2 - System Design', 'medium'),
('In a distributed system, what is the main role of a Cache?', '["Compile code", "Store persistent data", "Render UI", "Distribute traffic"]'::jsonb, 3, 'Year 2 - System Design', 'medium'),
('In a distributed system, what is the main role of a Message Queue?', '["Render UI", "Distribute traffic", "Store persistent data", "Compile code"]'::jsonb, 1, 'Year 2 - System Design', 'medium'),
('In a distributed system, what is the main role of a Database Index?', '["Render UI", "Store persistent data", "Distribute traffic", "Compile code"]'::jsonb, 2, 'Year 2 - System Design', 'medium'),
('In a distributed system, what is the main role of a Load Balancer?', '["Store persistent data", "Distribute traffic", "Render UI", "Compile code"]'::jsonb, 1, 'Year 2 - System Design', 'medium'),
('According to the CAP theorem, which two guarantees can a distributed data store provide simultaneously? (Scenario 0)', '["Consistency and Partition Tolerance", "Consistency and Availability", "Any two of the three", "Availability and Partition Tolerance"]'::jsonb, 2, 'Year 2 - System Design', 'hard'),
('According to the CAP theorem, which two guarantees can a distributed data store provide simultaneously? (Scenario 1)', '["Consistency and Availability", "Availability and Partition Tolerance", "Consistency and Partition Tolerance", "Any two of the three"]'::jsonb, 3, 'Year 2 - System Design', 'hard'),
('According to the CAP theorem, which two guarantees can a distributed data store provide simultaneously? (Scenario 2)', '["Any two of the three", "Availability and Partition Tolerance", "Consistency and Availability", "Consistency and Partition Tolerance"]'::jsonb, 0, 'Year 2 - System Design', 'hard'),
('According to the CAP theorem, which two guarantees can a distributed data store provide simultaneously? (Scenario 3)', '["Any two of the three", "Availability and Partition Tolerance", "Consistency and Partition Tolerance", "Consistency and Availability"]'::jsonb, 0, 'Year 2 - System Design', 'hard'),
('According to the CAP theorem, which two guarantees can a distributed data store provide simultaneously? (Scenario 4)', '["Consistency and Availability", "Consistency and Partition Tolerance", "Any two of the three", "Availability and Partition Tolerance"]'::jsonb, 2, 'Year 2 - System Design', 'hard'),
('According to the CAP theorem, which two guarantees can a distributed data store provide simultaneously? (Scenario 5)', '["Consistency and Availability", "Availability and Partition Tolerance", "Any two of the three", "Consistency and Partition Tolerance"]'::jsonb, 2, 'Year 2 - System Design', 'hard'),
('According to the CAP theorem, which two guarantees can a distributed data store provide simultaneously? (Scenario 6)', '["Consistency and Partition Tolerance", "Any two of the three", "Availability and Partition Tolerance", "Consistency and Availability"]'::jsonb, 1, 'Year 2 - System Design', 'hard'),
('According to the CAP theorem, which two guarantees can a distributed data store provide simultaneously? (Scenario 7)', '["Availability and Partition Tolerance", "Consistency and Partition Tolerance", "Consistency and Availability", "Any two of the three"]'::jsonb, 3, 'Year 2 - System Design', 'hard'),
('According to the CAP theorem, which two guarantees can a distributed data store provide simultaneously? (Scenario 8)', '["Consistency and Partition Tolerance", "Consistency and Availability", "Any two of the three", "Availability and Partition Tolerance"]'::jsonb, 2, 'Year 2 - System Design', 'hard'),
('According to the CAP theorem, which two guarantees can a distributed data store provide simultaneously? (Scenario 9)', '["Any two of the three", "Consistency and Partition Tolerance", "Consistency and Availability", "Availability and Partition Tolerance"]'::jsonb, 0, 'Year 2 - System Design', 'hard'),
('According to the CAP theorem, which two guarantees can a distributed data store provide simultaneously? (Scenario 10)', '["Consistency and Availability", "Consistency and Partition Tolerance", "Any two of the three", "Availability and Partition Tolerance"]'::jsonb, 2, 'Year 2 - System Design', 'hard'),
('Which database type is most appropriate for highly connected data like social networks? (Relational DB context)', '["Key-Value Store", "Document Store", "Relational DB", "Graph DB"]'::jsonb, 3, 'Year 2 - System Design', 'medium'),
('Which database type is most appropriate for highly connected data like social networks? (Document Store context)', '["Document Store", "Key-Value Store", "Relational DB", "Graph DB"]'::jsonb, 3, 'Year 2 - System Design', 'medium'),
('Which database type is most appropriate for highly connected data like social networks? (Key-Value Store context)', '["Graph DB", "Relational DB", "Document Store", "Key-Value Store"]'::jsonb, 0, 'Year 2 - System Design', 'medium'),
('Which database type is most appropriate for highly connected data like social networks? (Graph DB context)', '["Relational DB", "Key-Value Store", "Document Store", "Graph DB"]'::jsonb, 3, 'Year 2 - System Design', 'medium'),
('Which database type is most appropriate for highly connected data like social networks? (Time-Series DB context)', '["Relational DB", "Document Store", "Key-Value Store", "Graph DB"]'::jsonb, 3, 'Year 2 - System Design', 'medium'),
('Which database type is most appropriate for highly connected data like social networks? (Relational DB context)', '["Graph DB", "Document Store", "Key-Value Store", "Relational DB"]'::jsonb, 0, 'Year 2 - System Design', 'medium'),
('Which database type is most appropriate for highly connected data like social networks? (Document Store context)', '["Graph DB", "Document Store", "Relational DB", "Key-Value Store"]'::jsonb, 0, 'Year 2 - System Design', 'medium'),
('Which database type is most appropriate for highly connected data like social networks? (Key-Value Store context)', '["Document Store", "Key-Value Store", "Relational DB", "Graph DB"]'::jsonb, 3, 'Year 2 - System Design', 'medium'),
('Which database type is most appropriate for highly connected data like social networks? (Graph DB context)', '["Graph DB", "Document Store", "Relational DB", "Key-Value Store"]'::jsonb, 0, 'Year 2 - System Design', 'medium'),
('Which database type is most appropriate for highly connected data like social networks? (Time-Series DB context)', '["Key-Value Store", "Graph DB", "Document Store", "Relational DB"]'::jsonb, 1, 'Year 2 - System Design', 'medium'),
('Which database type is most appropriate for highly connected data like social networks? (Relational DB context)', '["Graph DB", "Relational DB", "Document Store", "Key-Value Store"]'::jsonb, 0, 'Year 2 - System Design', 'medium'),
('In how many ways can 3 distinct books be arranged on a shelf?', '["7", "5", "6", "12"]'::jsonb, 2, 'Year 2 - Advanced Aptitude', 'hard'),
('In how many ways can 4 distinct books be arranged on a shelf?', '["23", "25", "48", "24"]'::jsonb, 3, 'Year 2 - Advanced Aptitude', 'hard'),
('In how many ways can 5 distinct books be arranged on a shelf?', '["240", "120", "119", "121"]'::jsonb, 1, 'Year 2 - Advanced Aptitude', 'hard'),
('In how many ways can 6 distinct books be arranged on a shelf?', '["1440", "719", "720", "721"]'::jsonb, 2, 'Year 2 - Advanced Aptitude', 'hard'),
('In how many ways can 7 distinct books be arranged on a shelf?', '["10080", "5041", "5039", "5040"]'::jsonb, 3, 'Year 2 - Advanced Aptitude', 'hard'),
('In how many ways can 8 distinct books be arranged on a shelf?', '["40321", "80640", "40320", "40319"]'::jsonb, 2, 'Year 2 - Advanced Aptitude', 'hard'),
('In how many ways can 9 distinct books be arranged on a shelf?', '["725760", "362880", "362881", "362879"]'::jsonb, 1, 'Year 2 - Advanced Aptitude', 'hard'),
('In how many ways can 10 distinct books be arranged on a shelf?', '["3628800", "7257600", "3628799", "3628801"]'::jsonb, 0, 'Year 2 - Advanced Aptitude', 'hard'),
('In how many ways can 11 distinct books be arranged on a shelf?', '["39916799", "39916801", "79833600", "39916800"]'::jsonb, 3, 'Year 2 - Advanced Aptitude', 'hard'),
('In how many ways can 12 distinct books be arranged on a shelf?', '["479001601", "479001600", "958003200", "479001599"]'::jsonb, 1, 'Year 2 - Advanced Aptitude', 'hard'),
('In how many ways can 13 distinct books be arranged on a shelf?', '["6227020800", "6227020801", "12454041600", "6227020799"]'::jsonb, 0, 'Year 2 - Advanced Aptitude', 'hard'),
('A bag contains 2 red balls and 3 blue balls. What is the probability of drawing a red ball?', '["2/5", "3/5", "2/3", "1/5"]'::jsonb, 0, 'Year 2 - Advanced Aptitude', 'medium'),
('A bag contains 3 red balls and 4 blue balls. What is the probability of drawing a red ball?', '["4/7", "3/7", "1/7", "3/4"]'::jsonb, 1, 'Year 2 - Advanced Aptitude', 'medium'),
('A bag contains 4 red balls and 5 blue balls. What is the probability of drawing a red ball?', '["5/9", "4/5", "4/9", "1/9"]'::jsonb, 2, 'Year 2 - Advanced Aptitude', 'medium'),
('A bag contains 5 red balls and 6 blue balls. What is the probability of drawing a red ball?', '["1/11", "6/11", "5/11", "5/6"]'::jsonb, 2, 'Year 2 - Advanced Aptitude', 'medium'),
('A bag contains 6 red balls and 7 blue balls. What is the probability of drawing a red ball?', '["1/13", "6/13", "7/13", "6/7"]'::jsonb, 1, 'Year 2 - Advanced Aptitude', 'medium'),
('A bag contains 7 red balls and 8 blue balls. What is the probability of drawing a red ball?', '["1/15", "7/15", "8/15", "7/8"]'::jsonb, 1, 'Year 2 - Advanced Aptitude', 'medium'),
('A bag contains 8 red balls and 9 blue balls. What is the probability of drawing a red ball?', '["1/17", "8/17", "8/9", "9/17"]'::jsonb, 1, 'Year 2 - Advanced Aptitude', 'medium'),
('A bag contains 9 red balls and 10 blue balls. What is the probability of drawing a red ball?', '["9/10", "1/19", "10/19", "9/19"]'::jsonb, 3, 'Year 2 - Advanced Aptitude', 'medium'),
('A bag contains 10 red balls and 11 blue balls. What is the probability of drawing a red ball?', '["10/11", "11/21", "10/21", "1/21"]'::jsonb, 2, 'Year 2 - Advanced Aptitude', 'medium'),
('A bag contains 11 red balls and 12 blue balls. What is the probability of drawing a red ball?', '["12/23", "11/23", "11/12", "1/23"]'::jsonb, 1, 'Year 2 - Advanced Aptitude', 'medium'),
('A bag contains 12 red balls and 13 blue balls. What is the probability of drawing a red ball?', '["1/25", "12/25", "12/13", "13/25"]'::jsonb, 1, 'Year 2 - Advanced Aptitude', 'medium'),
('If a boat travels 10 km/hr in still water and the river flows at 2 km/hr, what is the downstream speed?', '["16", "10", "12", "14"]'::jsonb, 2, 'Year 2 - Advanced Aptitude', 'medium'),
('If a boat travels 11 km/hr in still water and the river flows at 3 km/hr, what is the downstream speed?', '["18", "16", "14", "12"]'::jsonb, 2, 'Year 2 - Advanced Aptitude', 'medium'),
('If a boat travels 12 km/hr in still water and the river flows at 4 km/hr, what is the downstream speed?', '["16", "18", "20", "14"]'::jsonb, 0, 'Year 2 - Advanced Aptitude', 'medium'),
('If a boat travels 13 km/hr in still water and the river flows at 5 km/hr, what is the downstream speed?', '["20", "18", "22", "16"]'::jsonb, 1, 'Year 2 - Advanced Aptitude', 'medium'),
('If a boat travels 14 km/hr in still water and the river flows at 6 km/hr, what is the downstream speed?', '["18", "20", "24", "22"]'::jsonb, 1, 'Year 2 - Advanced Aptitude', 'medium'),
('If a boat travels 15 km/hr in still water and the river flows at 7 km/hr, what is the downstream speed?', '["26", "22", "24", "20"]'::jsonb, 1, 'Year 2 - Advanced Aptitude', 'medium'),
('If a boat travels 16 km/hr in still water and the river flows at 8 km/hr, what is the downstream speed?', '["28", "26", "24", "22"]'::jsonb, 2, 'Year 2 - Advanced Aptitude', 'medium'),
('If a boat travels 17 km/hr in still water and the river flows at 9 km/hr, what is the downstream speed?', '["28", "30", "24", "26"]'::jsonb, 3, 'Year 2 - Advanced Aptitude', 'medium'),
('If a boat travels 18 km/hr in still water and the river flows at 10 km/hr, what is the downstream speed?', '["32", "26", "28", "30"]'::jsonb, 2, 'Year 2 - Advanced Aptitude', 'medium'),
('If a boat travels 19 km/hr in still water and the river flows at 11 km/hr, what is the downstream speed?', '["28", "32", "34", "30"]'::jsonb, 3, 'Year 2 - Advanced Aptitude', 'medium'),
('If a boat travels 20 km/hr in still water and the river flows at 12 km/hr, what is the downstream speed?', '["34", "30", "36", "32"]'::jsonb, 3, 'Year 2 - Advanced Aptitude', 'medium');
