import 'app_user.dart';

/// Represents one student team within a batch.
///
/// Teams are auto-generated by the Placement Rep setting a [targetSize];
/// the system creates ⌈student_count / target_size⌉ teams and distributes
/// students evenly. The Rep can then manually reassign students and assign
/// a Team Leader per team.
class Team {
  final String id;
  final String batchId;
  final String teamName;
  final String? teamLeaderId;
  final int targetSize;
  final DateTime createdAt;
  final DateTime updatedAt;

  /// Members are populated lazily by [BatchService.fetchTeamWithMembers].
  final List<AppUser> members;

  const Team({
    required this.id,
    required this.batchId,
    required this.teamName,
    this.teamLeaderId,
    required this.targetSize,
    required this.createdAt,
    required this.updatedAt,
    this.members = const [],
  });

  factory Team.fromMap(Map<String, dynamic> data) {
    return Team(
      id: data['id'] as String,
      batchId: data['batch_id'] as String,
      teamName: data['team_name'] as String,
      teamLeaderId: data['team_leader_id'] as String?,
      targetSize: data['target_size'] as int? ?? 6,
      createdAt: DateTime.parse(data['created_at'] as String),
      updatedAt: DateTime.parse(data['updated_at'] as String),
    );
  }

  Map<String, dynamic> toMap() => {
        'id': id,
        'batch_id': batchId,
        'team_name': teamName,
        'team_leader_id': teamLeaderId,
        'target_size': targetSize,
        'created_at': createdAt.toIso8601String(),
        'updated_at': updatedAt.toIso8601String(),
      };

  Team copyWith({
    String? teamLeaderId,
    int? targetSize,
    String? teamName,
    List<AppUser>? members,
  }) {
    return Team(
      id: id,
      batchId: batchId,
      teamName: teamName ?? this.teamName,
      teamLeaderId: teamLeaderId ?? this.teamLeaderId,
      targetSize: targetSize ?? this.targetSize,
      createdAt: createdAt,
      updatedAt: DateTime.now(),
      members: members ?? this.members,
    );
  }

  int get memberCount => members.length;

  @override
  bool operator ==(Object other) =>
      identical(this, other) || (other is Team && other.id == id);

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() =>
      'Team($teamName, leader: $teamLeaderId, size: ${members.length})';
}
