INSERT INTO question_bank (question_text, options, correct_option, topic, difficulty, is_active) VALUES
('What is 45% of 320?', '["144","140","150","136"]'::jsonb, 0, 'aptitude', 'easy', true),
('If 60% of a number is 138, what is the number?', '["230","225","240","210"]'::jsonb, 0, 'aptitude', 'easy', true),
('A number is first increased by 20% and then decreased by 20%. What is the net percentage change?', '["No change","4% decrease","4% increase","20% decrease"]'::jsonb, 1, 'aptitude', 'medium', true),
('In an election between two candidates, the winner secures 56% of the total 4500 votes polled. What is the winning margin?', '["540","450","630","360"]'::jsonb, 0, 'aptitude', 'medium', true),
('The price of an item is increased by 25%. By what percentage must the new price be decreased to restore the original price?', '["25%","20%","30%","16.67%"]'::jsonb, 1, 'aptitude', 'medium', true),
('A student scores 462 marks out of a maximum of 700. What percentage of marks did the student score?', '["66%","64%","68%","70%"]'::jsonb, 0, 'aptitude', 'easy', true),
('In a class of 60 students, 35% are girls. How many boys are there in the class?', '["39","21","36","24"]'::jsonb, 0, 'aptitude', 'easy', true),
('A''s salary is 20% more than B''s salary. By what percentage is B''s salary less than A''s?', '["20%","16.67%","25%","15%"]'::jsonb, 1, 'aptitude', 'hard', true),
('The population of a town increases by 10% every year. If the current population is 5000, what will it be after 2 years?', '["6050","6000","6100","5500"]'::jsonb, 0, 'aptitude', 'medium', true),
('A mixture of 30 litres contains milk and water such that 40% of it is milk. How many litres of water are in the mixture?', '["18","12","15","20"]'::jsonb, 0, 'aptitude', 'easy', true),
('If x is 150% of y, then y is what percentage of x?', '["150%","75%","66.67%","60%"]'::jsonb, 2, 'aptitude', 'medium', true),
('A shopkeeper''s daily sales increased from 250 units to 300 units. What is the percentage increase in sales?', '["20%","25%","15%","10%"]'::jsonb, 0, 'aptitude', 'easy', true),
('Three-fourths of a number is 25% more than 60. Find the number.', '["100","90","80","120"]'::jsonb, 0, 'aptitude', 'hard', true),
('Ravi earns Rs.25000 per month and spends 80% of it. How much does he save every month?', '["Rs.5000","Rs.4500","Rs.5500","Rs.6000"]'::jsonb, 0, 'aptitude', 'easy', true),
('Two numbers are respectively 20% and 50% more than a third number. What is the ratio of the first number to the second number?', '["4:5","5:4","2:3","3:2"]'::jsonb, 0, 'aptitude', 'hard', true),
('A shopkeeper buys an article for Rs.500 and sells it for Rs.600. What is his profit percentage?', '["20%","15%","25%","10%"]'::jsonb, 0, 'aptitude', 'easy', true),
('An item is sold for Rs.720 at a loss of 10%. What was the cost price?', '["Rs.800","Rs.750","Rs.850","Rs.792"]'::jsonb, 0, 'aptitude', 'easy', true),
('A shopkeeper marks up an item by 40% and then gives a discount of 20%. What is his net profit percentage?', '["12%","16%","20%","8%"]'::jsonb, 0, 'aptitude', 'medium', true),
('By selling a table for Rs.1140, a carpenter loses 5%. At what price should he sell it to gain 10%?', '["Rs.1320","Rs.1260","Rs.1300","Rs.1254"]'::jsonb, 0, 'aptitude', 'medium', true),
('A trader buys goods at Rs.250 and sells them at Rs.200. Find the loss percentage.', '["20%","25%","15%","10%"]'::jsonb, 0, 'aptitude', 'easy', true),
('A man buys two watches for a total of Rs.700. He sells one at a profit of 20% and the other at a loss of 15%, and on the whole transaction he neither gains nor loses. Find the cost price of the watch sold at a profit.', '["Rs.300","Rs.400","Rs.350","Rs.280"]'::jsonb, 0, 'aptitude', 'medium', true),
('A retailer buys a shirt for Rs.400 and marks it up to Rs.500. What is the mark-up percentage?', '["25%","20%","15%","30%"]'::jsonb, 0, 'aptitude', 'easy', true),
('The cost price of 15 articles is equal to the selling price of 12 articles. Find the profit percentage.', '["25%","20%","15%","30%"]'::jsonb, 0, 'aptitude', 'medium', true),
('A dishonest dealer professes to sell his goods at cost price but uses a weight of 800 gm instead of 1 kg. Find his profit percentage.', '["25%","20%","16.67%","30%"]'::jsonb, 0, 'aptitude', 'easy', true),
('A man sold two articles, each for Rs.990. On one he gains 10% and on the other he loses 10%. Find his overall gain or loss percentage.', '["1% loss","1% gain","No profit no loss","2% loss"]'::jsonb, 0, 'aptitude', 'medium', true);
INSERT INTO question_bank (question_text, options, correct_option, topic, difficulty, is_active) VALUES
('A vendor sells an item for Rs.360, incurring a loss of Rs.40. Find the cost price.', '["Rs.400","Rs.380","Rs.420","Rs.360"]'::jsonb, 0, 'aptitude', 'easy', true),
('A shopkeeper allows a discount of 10% on the marked price but still makes a profit of 26%. If the cost price of the article is Rs.500, find the marked price.', '["Rs.700","Rs.680","Rs.720","Rs.750"]'::jsonb, 0, 'aptitude', 'hard', true),
('An article is sold at a gain of 15%. Had it been sold for Rs.30 more, the gain would have been 20%. Find the cost price.', '["Rs.600","Rs.500","Rs.650","Rs.550"]'::jsonb, 0, 'aptitude', 'medium', true),
('A trader marks his goods 50% above cost price and allows a discount of 25% for cash payment. What is his profit percentage?', '["12.5%","15%","10%","20%"]'::jsonb, 0, 'aptitude', 'hard', true),
('By selling a pen for Rs.66, a shopkeeper gains 10%. Find the cost price of the pen.', '["Rs.60","Rs.56","Rs.64","Rs.62"]'::jsonb, 0, 'aptitude', 'easy', true),
('Divide Rs.1200 among A, B and C in the ratio 2:3:5. Find B''s share.', '["Rs.360","Rs.240","Rs.400","Rs.300"]'::jsonb, 0, 'aptitude', 'easy', true),
('If a:b = 3:4 and b:c = 4:5, find a:b:c.', '["3:4:5","3:5:4","4:3:5","5:4:3"]'::jsonb, 0, 'aptitude', 'easy', true),
('Two numbers are in the ratio 5:7. If their sum is 144, find the larger number.', '["84","80","90","72"]'::jsonb, 0, 'aptitude', 'medium', true),
('If 20 men can build a wall in 15 days, in how many days can 25 men build the same wall, assuming the same work rate per man?', '["12","10","15","18"]'::jsonb, 0, 'aptitude', 'medium', true),
('The ratio of two numbers is 4:5 and their HCF is 6. Find the LCM.', '["120","100","90","150"]'::jsonb, 0, 'aptitude', 'easy', true),
('A sum of money is divided among P, Q and R in the ratio 3:5:7. If R gets Rs.420 more than P, find the total sum.', '["Rs.1575","Rs.1500","Rs.1680","Rs.1400"]'::jsonb, 0, 'aptitude', 'medium', true),
('If a:b=2:3, c:d=4:5, and a:d=8:15, find b:c.', '["1:1","3:4","4:3","2:3"]'::jsonb, 0, 'aptitude', 'medium', true),
('The ratio of boys to girls in a class is 3:2. If there are 18 boys, how many girls are there?', '["12","15","10","14"]'::jsonb, 0, 'aptitude', 'easy', true),
('Rs.1700 is divided among A, B and C such that A gets 2/3 of what B gets, and B gets 1/4 of what C gets. Find C''s share.', '["Rs.1200","Rs.1000","Rs.1100","Rs.1300"]'::jsonb, 0, 'aptitude', 'hard', true),
('The ratio of the ages of A and B is 3:5. After 10 years, the ratio becomes 5:7. Find A''s present age.', '["15","20","12","18"]'::jsonb, 0, 'aptitude', 'hard', true),
('Two numbers are in the ratio 3:4. If 8 is added to each, the ratio becomes 5:6. Find the numbers.', '["12 and 16","15 and 20","9 and 12","18 and 24"]'::jsonb, 0, 'aptitude', 'medium', true),
('If the ratio of two numbers is 7:9 and their LCM is 252, find the numbers.', '["28 and 36","21 and 27","14 and 18","35 and 45"]'::jsonb, 0, 'aptitude', 'easy', true),
('A car travels 180 km in 3 hours. Find its speed.', '["60 km/h","50 km/h","65 km/h","55 km/h"]'::jsonb, 0, 'aptitude', 'easy', true),
('A man walks at a speed of 5 km/h. How much time will he take to cover 20 km?', '["4 hours","5 hours","3 hours","4.5 hours"]'::jsonb, 0, 'aptitude', 'easy', true),
('A train 150 m long crosses a pole in 15 seconds. Find its speed in km/h.', '["36 km/h","30 km/h","40 km/h","45 km/h"]'::jsonb, 0, 'aptitude', 'medium', true),
('Two trains 120 m and 180 m long run in opposite directions on parallel tracks at 54 km/h and 36 km/h respectively. Find the time they take to cross each other.', '["12 seconds","10 seconds","15 seconds","8 seconds"]'::jsonb, 0, 'aptitude', 'medium', true),
('A cyclist covers a distance of 90 km in 4 hours, partly at 20 km/h and partly at 30 km/h. Find the distance covered at 30 km/h.', '["30 km","40 km","20 km","35 km"]'::jsonb, 0, 'aptitude', 'medium', true),
('Convert a speed of 72 km/h into m/s.', '["20 m/s","18 m/s","22 m/s","25 m/s"]'::jsonb, 0, 'aptitude', 'easy', true),
('A person travels from A to B at 40 km/h and returns from B to A at 60 km/h. Find his average speed for the entire journey.', '["48 km/h","50 km/h","45 km/h","52 km/h"]'::jsonb, 0, 'aptitude', 'hard', true),
('A train running at 90 km/h crosses a platform 250 m long in 20 seconds. Find the length of the train.', '["250 m","200 m","300 m","220 m"]'::jsonb, 0, 'aptitude', 'medium', true);
INSERT INTO question_bank (question_text, options, correct_option, topic, difficulty, is_active) VALUES
('Two cars start from the same point at the same time and travel in the same direction. Car A travels at 60 km/h and car B at 75 km/h. After how many hours will they be 45 km apart?', '["3 hours","2.5 hours","4 hours","3.5 hours"]'::jsonb, 0, 'aptitude', 'easy', true),
('A bus covers a certain distance at 40 km/h in 6 hours. How long will it take to cover the same distance at 60 km/h?', '["4 hours","5 hours","4.5 hours","3.5 hours"]'::jsonb, 0, 'aptitude', 'easy', true),
('Excluding stoppages, a train travels at 60 km/h, and including stoppages it travels at 50 km/h. For how many minutes does the train stop per hour?', '["10 minutes","12 minutes","8 minutes","15 minutes"]'::jsonb, 0, 'aptitude', 'medium', true),
('A thief is spotted by a policeman from a distance of 200 m. When the policeman starts the chase, the thief also starts running. If the speed of the thief is 10 km/h and that of the policeman is 12 km/h, find the distance the thief runs before being caught.', '["1000 m","800 m","1200 m","900 m"]'::jsonb, 0, 'aptitude', 'hard', true),
('A man walks 3 km in 45 minutes. What is his speed in km/h?', '["4 km/h","3.5 km/h","4.5 km/h","5 km/h"]'::jsonb, 0, 'aptitude', 'easy', true),
('A train travels 360 km at a uniform speed. If the speed had been 5 km/h more, it would have taken 1 hour less for the same journey. Find the original speed.', '["40 km/h","45 km/h","35 km/h","50 km/h"]'::jsonb, 0, 'aptitude', 'medium', true),
('A man can complete a journey in 10 hours. He travels the first half of the journey at 21 km/h and the second half at 24 km/h. Find the total distance.', '["224 km","220 km","230 km","210 km"]'::jsonb, 0, 'aptitude', 'hard', true),
('A can do a piece of work in 10 days and B can do it in 15 days. In how many days will they finish it working together?', '["6 days","7 days","8 days","5 days"]'::jsonb, 0, 'aptitude', 'easy', true),
('A can complete a work in 20 days. What fraction of the work does he do in 4 days?', '["1/5","1/4","1/6","2/5"]'::jsonb, 0, 'aptitude', 'easy', true),
('A and B together can complete a work in 12 days. A alone can do it in 20 days. In how many days can B alone complete the work?', '["30 days","25 days","28 days","24 days"]'::jsonb, 0, 'aptitude', 'medium', true),
('12 men can complete a work in 18 days. In how many days will 8 men complete the same work?', '["27 days","24 days","30 days","20 days"]'::jsonb, 0, 'aptitude', 'medium', true),
('A can do a work in 12 days and B in 15 days. They work together for 4 days and then A leaves. In how many more days will B finish the remaining work?', '["6 days","5 days","7 days","8 days"]'::jsonb, 0, 'aptitude', 'hard', true),
('A can do a piece of work in 8 days and B in 12 days. If they work on alternate days starting with A, in how many days will the work be completed?', '["9.5 days","9 days","10 days","8.5 days"]'::jsonb, 0, 'aptitude', 'medium', true),
('If 6 workers can build a wall in 10 days, how many workers are needed to build it in 5 days, assuming the same work rate per worker?', '["12","10","15","8"]'::jsonb, 0, 'aptitude', 'easy', true),
('A, B and C can complete a job in 10, 15 and 30 days respectively. In how many days can they complete the job working together?', '["5 days","6 days","4 days","7 days"]'::jsonb, 0, 'aptitude', 'medium', true),
('A can do 1/3 of a work in 5 days and B can do 2/5 of the work in 10 days. In how many days can both together complete the work?', '["9.375 days","10 days","9 days","8.5 days"]'::jsonb, 0, 'aptitude', 'hard', true),
('Pipe A can fill a tank in 6 hours and pipe B can empty it in 10 hours. If both pipes are opened together, in how many hours will the tank be filled?', '["15 hours","12 hours","18 hours","10 hours"]'::jsonb, 0, 'aptitude', 'medium', true),
('A can finish a work in 15 days working 8 hours a day. In how many days can he finish it working 10 hours a day?', '["12 days","10 days","14 days","15 days"]'::jsonb, 0, 'aptitude', 'easy', true),
('20 men can complete a work in 15 days. After 5 days, 5 more men join them. In how many total days will the work be completed?', '["13 days","12 days","14 days","15 days"]'::jsonb, 0, 'aptitude', 'hard', true),
('A is twice as efficient as B. If B can complete a work in 24 days, in how many days can A and B together complete the work?', '["8 days","9 days","10 days","6 days"]'::jsonb, 0, 'aptitude', 'medium', true),
('Three taps can fill a tank in 12, 15 and 20 hours respectively. If all three are opened together, find the time to fill the tank.', '["5 hours","6 hours","4 hours","7 hours"]'::jsonb, 0, 'aptitude', 'easy', true),
('A can do a work in 18 days and B is 50% more efficient than A. In how many days can B alone complete the work?', '["12 days","14 days","10 days","15 days"]'::jsonb, 0, 'aptitude', 'medium', true),
('Find the simple interest on Rs.5000 at 8% per annum for 3 years.', '["Rs.1200","Rs.1000","Rs.1500","Rs.1100"]'::jsonb, 0, 'aptitude', 'easy', true),
('A sum of Rs.4000 amounts to Rs.4800 in 4 years at simple interest. Find the rate of interest.', '["5%","4%","6%","8%"]'::jsonb, 0, 'aptitude', 'easy', true),
('In how many years will a sum of Rs.6000 become Rs.7800 at 10% per annum simple interest?', '["3 years","2.5 years","4 years","3.5 years"]'::jsonb, 0, 'aptitude', 'medium', true);
INSERT INTO question_bank (question_text, options, correct_option, topic, difficulty, is_active) VALUES
('A sum of money doubles itself in 8 years at simple interest. Find the rate of interest per annum.', '["12.5%","10%","15%","8%"]'::jsonb, 0, 'aptitude', 'medium', true),
('Find the principal that yields a simple interest of Rs.900 in 3 years at 6% per annum.', '["Rs.5000","Rs.4500","Rs.5500","Rs.6000"]'::jsonb, 0, 'aptitude', 'easy', true),
('A sum was invested at simple interest at a certain rate for 3 years. Had it been invested at a rate 2% higher, it would have earned Rs.360 more. Find the sum.', '["Rs.6000","Rs.5000","Rs.7000","Rs.6500"]'::jsonb, 0, 'aptitude', 'hard', true),
('Rs.3000 is lent at 5% per annum simple interest for the first 2 years, and then at 8% per annum for the next 3 years. Find the total interest earned.', '["Rs.1020","Rs.1000","Rs.1100","Rs.950"]'::jsonb, 0, 'aptitude', 'medium', true),
('A certain sum amounts to Rs.2900 in 3 years and Rs.3200 in 5 years at simple interest. Find the sum.', '["Rs.2450","Rs.2400","Rs.2500","Rs.2350"]'::jsonb, 0, 'aptitude', 'hard', true),
('Find the compound interest on Rs.10000 at 10% per annum for 2 years, compounded annually.', '["Rs.2100","Rs.2000","Rs.2200","Rs.1900"]'::jsonb, 0, 'aptitude', 'easy', true),
('Find the amount on Rs.8000 at 5% per annum compound interest for 3 years.', '["Rs.9261","Rs.9200","Rs.9300","Rs.9150"]'::jsonb, 0, 'aptitude', 'medium', true),
('The compound interest on a sum for 2 years at 10% per annum is Rs.420. Find the simple interest on the same sum for 2 years at the same rate.', '["Rs.400","Rs.420","Rs.380","Rs.450"]'::jsonb, 0, 'aptitude', 'medium', true),
('Find the compound interest on Rs.5000 for 1 year at 8% per annum, compounded half-yearly.', '["Rs.408","Rs.400","Rs.416","Rs.420"]'::jsonb, 0, 'aptitude', 'easy', true),
('A sum of money invested at compound interest amounts to Rs.4840 in 2 years and Rs.5324 in 3 years. Find the rate of interest per annum.', '["10%","8%","12%","9%"]'::jsonb, 0, 'aptitude', 'hard', true),
('Find the difference between compound interest and simple interest on Rs.6000 for 2 years at 5% per annum.', '["Rs.15","Rs.10","Rs.20","Rs.12"]'::jsonb, 0, 'aptitude', 'medium', true),
('At what rate percent per annum compound interest will a sum of Rs.2500 become Rs.3025 in 2 years?', '["10%","12%","8%","11%"]'::jsonb, 0, 'aptitude', 'hard', true),
('Find the compound interest on Rs.15000 at 10% per annum for 1 year, compounded annually.', '["Rs.1500","Rs.1600","Rs.1400","Rs.1550"]'::jsonb, 0, 'aptitude', 'easy', true),
('A sum of Rs.12000 is invested at 10% per annum compound interest for 2 years. Find the compound interest.', '["Rs.2520","Rs.2400","Rs.2600","Rs.2450"]'::jsonb, 0, 'aptitude', 'medium', true),
('The population of a village grows at 5% per annum compounded annually. If the population 2 years ago was 8000, find the current population.', '["8820","8800","8750","8900"]'::jsonb, 0, 'aptitude', 'easy', true),
('Find the average of the first 10 natural numbers.', '["5.5","5","6","4.5"]'::jsonb, 0, 'aptitude', 'easy', true),
('The average of 5 numbers is 20. If one number is excluded, the average becomes 19. Find the excluded number.', '["24","20","25","22"]'::jsonb, 0, 'aptitude', 'easy', true),
('The average age of 30 students in a class is 12 years. If the teacher''s age is included, the average becomes 13 years. Find the teacher''s age.', '["43","40","45","42"]'::jsonb, 0, 'aptitude', 'medium', true),
('The average weight of 8 persons increases by 2.5 kg when a new person replaces one of them weighing 65 kg. Find the weight of the new person.', '["85 kg","80 kg","90 kg","75 kg"]'::jsonb, 0, 'aptitude', 'medium', true),
('Find the average of the first 20 multiples of 5.', '["52.5","50","55","57.5"]'::jsonb, 0, 'aptitude', 'easy', true),
('The average of 11 numbers is 60. The average of the first 6 numbers is 58 and that of the last 6 numbers is 63. Find the 6th number.', '["66","64","68","62"]'::jsonb, 0, 'aptitude', 'hard', true),
('A cricketer has a certain average of runs for 12 innings. In the 13th innings he scores 96 runs, increasing his average by 5. Find his new average.', '["36","34","38","32"]'::jsonb, 0, 'aptitude', 'medium', true),
('Find the average of five consecutive integers starting from 14.', '["16","15","17","18"]'::jsonb, 0, 'aptitude', 'easy', true),
('The average marks of 40 students in a class is 65. If the average of 25 of them is 70, find the average of the remaining 15 students.', '["56.67","55","58","60"]'::jsonb, 0, 'aptitude', 'medium', true),
('The average salary of all workers in a factory is Rs.8000. The average salary of 12 technicians is Rs.12000 and the average salary of the rest is Rs.6000. Find the total number of workers.', '["36","30","40","32"]'::jsonb, 0, 'aptitude', 'hard', true);
INSERT INTO question_bank (question_text, options, correct_option, topic, difficulty, is_active) VALUES
('The average of 4 numbers is 25. If three of the numbers are 20, 25 and 30, find the fourth number.', '["25","20","30","15"]'::jsonb, 0, 'aptitude', 'easy', true),
('A batsman''s average after 16 innings is 36. After playing the 17th innings, his average increases by 2. Find the runs scored in the 17th innings.', '["70","68","72","66"]'::jsonb, 0, 'aptitude', 'easy', true),
('In how many ways can 5 different books be arranged on a shelf?', '["120","100","60","24"]'::jsonb, 0, 'aptitude', 'easy', true),
('Find the number of ways to select 3 students out of 8 for a committee.', '["56","48","64","36"]'::jsonb, 0, 'aptitude', 'easy', true),
('How many 3-digit numbers can be formed using digits 1,2,3,4,5 without repetition?', '["60","125","20","100"]'::jsonb, 0, 'aptitude', 'medium', true),
('In how many ways can the letters of the word "LEADER" be arranged?', '["360","720","180","240"]'::jsonb, 0, 'aptitude', 'medium', true),
('In how many ways can 4 men and 3 women be seated in a row such that no two women sit together?', '["1440","720","2880","360"]'::jsonb, 0, 'aptitude', 'hard', true),
('Find the value of 6C2 (the number of ways to choose 2 items from 6).', '["15","12","18","20"]'::jsonb, 0, 'aptitude', 'easy', true),
('How many different committees of 3 men and 2 women can be formed from 6 men and 4 women?', '["120","100","144","90"]'::jsonb, 0, 'aptitude', 'medium', true),
('In how many ways can 7 people be seated around a circular table?', '["720","5040","360","840"]'::jsonb, 0, 'aptitude', 'easy', true),
('How many 4-letter words (with or without meaning) can be formed using the letters of the word "NUMBER" without repetition?', '["360","720","240","480"]'::jsonb, 0, 'aptitude', 'medium', true),
('In how many ways can a coin be tossed 3 times to get exactly 2 heads?', '["3","4","2","6"]'::jsonb, 0, 'aptitude', 'easy', true),
('From a group of 5 men and 4 women, a committee of 4 is to be formed such that it includes at least 2 women. Find the number of ways.', '["81","75","90","70"]'::jsonb, 0, 'aptitude', 'hard', true),
('How many diagonals does a hexagon have?', '["9","8","12","6"]'::jsonb, 0, 'aptitude', 'medium', true),
('A die is rolled once. What is the probability of getting a number greater than 4?', '["1/3","1/2","1/6","2/3"]'::jsonb, 0, 'aptitude', 'easy', true),
('A coin is tossed twice. What is the probability of getting exactly one head?', '["1/2","1/4","3/4","1/3"]'::jsonb, 0, 'aptitude', 'easy', true),
('A bag contains 4 red and 6 black balls. One ball is drawn at random. Find the probability that it is red.', '["2/5","3/5","1/2","1/5"]'::jsonb, 0, 'aptitude', 'medium', true),
('Two dice are thrown together. Find the probability of getting a sum of 8.', '["5/36","6/36","4/36","7/36"]'::jsonb, 0, 'aptitude', 'medium', true),
('A bag contains 5 red, 4 blue and 3 green balls. Two balls are drawn at random. Find the probability that both are red.', '["5/33","5/22","1/6","5/66"]'::jsonb, 0, 'aptitude', 'hard', true),
('A card is drawn from a well-shuffled deck of 52 cards. Find the probability that it is a king.', '["1/13","1/26","1/4","1/52"]'::jsonb, 0, 'aptitude', 'easy', true),
('From a pack of 52 cards, one card is drawn. Find the probability that it is either a heart or a king.', '["4/13","17/52","1/4","5/13"]'::jsonb, 0, 'aptitude', 'medium', true),
('Three coins are tossed simultaneously. Find the probability of getting at least two heads.', '["1/2","3/8","5/8","1/4"]'::jsonb, 0, 'aptitude', 'hard', true),
('A bag contains 3 red and 5 black balls. Two balls are drawn at random without replacement. Find the probability that both are black.', '["5/14","5/8","3/14","1/4"]'::jsonb, 0, 'aptitude', 'medium', true),
('What is the probability of drawing an ace from a standard deck of 52 playing cards?', '["1/13","1/4","1/52","1/26"]'::jsonb, 0, 'aptitude', 'easy', true),
('In a class of 30 students, 18 play cricket, 12 play football, and 6 play both. If a student is selected at random, find the probability that the student plays neither sport.', '["1/5","1/6","1/4","2/15"]'::jsonb, 0, 'aptitude', 'hard', true);
INSERT INTO question_bank (question_text, options, correct_option, topic, difficulty, is_active) VALUES
('A number is selected at random from 1 to 25. Find the probability that it is a prime number.', '["9/25","8/25","1/3","10/25"]'::jsonb, 0, 'aptitude', 'medium', true),
('Find the next number in the series: 2, 4, 6, 8, __', '["10","12","9","11"]'::jsonb, 0, 'aptitude', 'easy', true),
('Find the next number in the series: 5, 10, 20, 40, __', '["80","60","70","90"]'::jsonb, 0, 'aptitude', 'easy', true),
('Find the next number in the series: 3, 6, 11, 18, 27, __', '["38","36","40","35"]'::jsonb, 0, 'aptitude', 'medium', true),
('Find the missing number in the series: 1, 4, 9, 16, 25, __', '["36","30","32","49"]'::jsonb, 0, 'aptitude', 'medium', true),
('Find the next number in the series: 2, 3, 5, 8, 13, 21, __', '["34","33","35","32"]'::jsonb, 0, 'aptitude', 'easy', true),
('Find the next number in the series: 100, 90, 80, 70, __', '["60","65","55","50"]'::jsonb, 0, 'aptitude', 'easy', true),
('Find the next term in the series: 4, 9, 16, 25, 36, __', '["49","48","64","42"]'::jsonb, 0, 'aptitude', 'medium', true),
('Find the next number in the series: 1, 2, 6, 24, 120, __', '["720","600","840","540"]'::jsonb, 0, 'aptitude', 'hard', true),
('Find the odd one out in the series (all except one are prime numbers): 3, 5, 7, 9, 11, 13', '["9","7","11","13"]'::jsonb, 0, 'aptitude', 'medium', true),
('Find the next number in the series: 7, 14, 21, 28, __', '["35","36","32","42"]'::jsonb, 0, 'aptitude', 'easy', true),
('Find the next number in the series: 1, 4, 10, 22, 46, __', '["94","90","92","96"]'::jsonb, 0, 'aptitude', 'hard', true),
('Find the missing number in the series: 6, 11, 21, 36, 56, __', '["81","80","85","76"]'::jsonb, 0, 'aptitude', 'medium', true),
('The present age of a father is 45 years and his son is 15 years. In how many years will the father''s age be twice the son''s age?', '["15 years","10 years","20 years","12 years"]'::jsonb, 0, 'aptitude', 'easy', true),
('A is 6 years older than B. If the sum of their ages is 36, find B''s age.', '["15","18","12","21"]'::jsonb, 0, 'aptitude', 'easy', true),
('Five years ago, a father''s age was 5 times his son''s age. Five years hence, the father''s age will be 3 times the son''s age. Find the present age of the father.', '["55","50","45","60"]'::jsonb, 0, 'aptitude', 'medium', true),
('The ratio of the present ages of A and B is 4:5. After 8 years, the ratio becomes 6:7. Find A''s present age.', '["16","20","12","24"]'::jsonb, 0, 'aptitude', 'medium', true),
('A father''s age is 3 times his son''s age. After 12 years, the father''s age will be twice his son''s age. Find the son''s present age.', '["12","10","15","14"]'::jsonb, 0, 'aptitude', 'easy', true),
('The average age of a family of 5 members is 24 years. If the age of the youngest member is 8 years, find the average age of the family at the time of the youngest member''s birth.', '["20","18","22","24"]'::jsonb, 0, 'aptitude', 'hard', true),
('A person''s age 10 years hence will be twice his age 10 years ago. Find his present age.', '["30","25","35","28"]'::jsonb, 0, 'aptitude', 'medium', true),
('The ratio of ages of two friends is 3:4. If the sum of their ages is 63, find the age of the younger friend.', '["27","28","24","30"]'::jsonb, 0, 'aptitude', 'easy', true),
('A man''s age is 4 times his son''s age. Five years ago, the man''s age was 7 times his son''s age. Find the man''s present age.', '["40","35","45","32"]'::jsonb, 0, 'aptitude', 'hard', true),
('The sum of ages of a father and his son is 60 years. Six years ago, the father''s age was 5 times the son''s age. Find the father''s present age.', '["46","44","48","42"]'::jsonb, 0, 'aptitude', 'medium', true),
('In what ratio must a shopkeeper mix tea worth Rs.60/kg with tea worth Rs.90/kg so that the mixture is worth Rs.70/kg?', '["2:1","1:2","3:2","1:1"]'::jsonb, 0, 'aptitude', 'easy', true);
INSERT INTO question_bank (question_text, options, correct_option, topic, difficulty, is_active) VALUES
('A vessel contains a mixture of milk and water in the ratio 5:1. How much water must be added to 24 litres of this mixture so that the ratio becomes 5:3?', '["8 litres","6 litres","10 litres","4 litres"]'::jsonb, 0, 'aptitude', 'medium', true),
('In what ratio should two varieties of rice priced at Rs.20/kg and Rs.30/kg be mixed so that the mixture costs Rs.24/kg?', '["3:2","2:3","1:2","2:1"]'::jsonb, 0, 'aptitude', 'medium', true),
('A mixture of 60 litres contains milk and water in the ratio 2:1. How much water should be added to make the ratio 1:2?', '["60 litres","50 litres","40 litres","70 litres"]'::jsonb, 0, 'aptitude', 'easy', true),
('A container has 40 litres of milk. 4 litres of milk is replaced with water, and this replacement process is repeated two more times (3 times in total). Find the quantity of milk left in the container.', '["29.16 litres","28 litres","30 litres","27.5 litres"]'::jsonb, 0, 'aptitude', 'hard', true),
('How many kg of sugar costing Rs.40/kg must be mixed with 20 kg of sugar costing Rs.25/kg so that the mixture is worth Rs.30/kg?', '["10 kg","12 kg","8 kg","15 kg"]'::jsonb, 0, 'aptitude', 'medium', true),
('A jar contains a mixture of two liquids A and B in the ratio 4:1. When 10 litres of the mixture is drawn off and replaced with liquid B, the ratio becomes 2:3. Find the initial quantity of liquid A in the jar.', '["16 litres","20 litres","12 litres","18 litres"]'::jsonb, 0, 'aptitude', 'hard', true),
('A trader mixes 26 kg of rice at Rs.20/kg with 30 kg of rice at Rs.36/kg. Find the average price of the mixture per kg.', '["Rs.28.57","Rs.28","Rs.29","Rs.27.5"]'::jsonb, 0, 'aptitude', 'medium', true),
('A boat''s speed in still water is 15 km/h and the speed of the stream is 3 km/h. Find the downstream speed.', '["18 km/h","15 km/h","12 km/h","21 km/h"]'::jsonb, 0, 'aptitude', 'easy', true),
('A man can row at 10 km/h in still water. If the speed of the stream is 2 km/h, find his upstream speed.', '["8 km/h","10 km/h","12 km/h","6 km/h"]'::jsonb, 0, 'aptitude', 'easy', true),
('A boat covers 32 km downstream in 4 hours. If the speed of the stream is 2 km/h, find the speed of the boat in still water.', '["6 km/h","8 km/h","10 km/h","4 km/h"]'::jsonb, 0, 'aptitude', 'medium', true),
('A man rows upstream 24 km in 6 hours and downstream 24 km in 4 hours. Find the speed of the stream.', '["1 km/h","2 km/h","1.5 km/h","0.5 km/h"]'::jsonb, 0, 'aptitude', 'medium', true),
('A boat takes 8 hours to travel a certain distance upstream and 6 hours to travel the same distance downstream. If the speed of the stream is 2 km/h, find the speed of the boat in still water.', '["14 km/h","12 km/h","16 km/h","10 km/h"]'::jsonb, 0, 'aptitude', 'hard', true),
('A boat''s speed in still water is 12 km/h and the speed of the current is 4 km/h. Find the time taken by the boat to go 32 km downstream.', '["2 hours","2.5 hours","3 hours","1.5 hours"]'::jsonb, 0, 'aptitude', 'medium', true),
('A man can row 30 km upstream and 44 km downstream in 10 hours. He can also row 40 km upstream and 55 km downstream in 13 hours. Find the speed of the boat in still water.', '["8 km/h","9 km/h","7 km/h","10 km/h"]'::jsonb, 0, 'aptitude', 'hard', true),
('The speed of a boat in still water is 20 km/h and the speed of the stream is 5 km/h. Find the total time taken by the boat to go 75 km downstream and return.', '["8 hours","7 hours","9 hours","6.5 hours"]'::jsonb, 0, 'aptitude', 'easy', true),
('Find the angle between the hour and minute hands of a clock at 3:00.', '["90 degrees","60 degrees","120 degrees","75 degrees"]'::jsonb, 0, 'aptitude', 'easy', true),
('Find the angle between the hour and minute hands of a clock at 4:30.', '["45 degrees","30 degrees","60 degrees","15 degrees"]'::jsonb, 0, 'aptitude', 'medium', true),
('At what time between 3 and 4 o''clock will the hands of a clock be together?', '["3:16 (4/11) minutes","3:15","3:18","3:20"]'::jsonb, 0, 'aptitude', 'medium', true),
('How many times do the hands of a clock coincide in a 24-hour day?', '["22","24","20","23"]'::jsonb, 0, 'aptitude', 'hard', true),
('Find the angle between the hour and minute hands of a clock at 6:00.', '["180 degrees","150 degrees","160 degrees","170 degrees"]'::jsonb, 0, 'aptitude', 'easy', true),
('A clock gains 10 minutes every 24 hours. If it is set to the correct time at 12 noon on Monday, what time will it show at 12 noon on Wednesday (48 hours later)?', '["12:20 PM","12:10 PM","12:30 PM","12:15 PM"]'::jsonb, 0, 'aptitude', 'hard', true),
('If today is Monday, what day will it be after 15 days?', '["Tuesday","Wednesday","Monday","Sunday"]'::jsonb, 0, 'aptitude', 'easy', true),
('January 1, 2024 was a Monday. What day of the week was January 1, 2025?', '["Wednesday","Tuesday","Thursday","Monday"]'::jsonb, 0, 'aptitude', 'medium', true),
('If the first day of a month is a Friday and the month has 31 days, what day of the week is the last day of the month?', '["Sunday","Saturday","Monday","Friday"]'::jsonb, 0, 'aptitude', 'medium', true),
('How many odd days are there in 100 years?', '["5","3","1","4"]'::jsonb, 0, 'aptitude', 'easy', true);
INSERT INTO question_bank (question_text, options, correct_option, topic, difficulty, is_active) VALUES
('What day of the week was 15th August 1947?', '["Friday","Thursday","Saturday","Sunday"]'::jsonb, 0, 'aptitude', 'hard', true),
('If 1st January 2023 is a Sunday, find the day of the week on 1st January 2027.', '["Friday","Thursday","Saturday","Monday"]'::jsonb, 0, 'aptitude', 'hard', true),
('The following table shows the sales (in units) of a shop over 4 days: Mon-120, Tue-150, Wed-90, Thu-140. Find the average daily sales.', '["125","130","120","135"]'::jsonb, 0, 'aptitude', 'easy', true),
('A company''s profit in 2020 was Rs.2,00,000 and in 2021 it was Rs.2,50,000. Find the percentage increase in profit.', '["25%","20%","30%","22%"]'::jsonb, 0, 'aptitude', 'easy', true),
('In a survey of 200 people, 120 preferred tea and the rest preferred coffee. What percentage of people preferred coffee?', '["40%","60%","35%","45%"]'::jsonb, 0, 'aptitude', 'medium', true),
('The marks obtained by a student in 5 subjects are 78, 84, 92, 66 and 80. Find the average marks obtained.', '["80","78","82","76"]'::jsonb, 0, 'aptitude', 'medium', true),
('Find the odd one out: 8, 27, 64, 100, 125', '["100","64","125","27"]'::jsonb, 0, 'aptitude', 'easy', true),
('In a certain code, letters are replaced by their alphabet position numbers written together: CAT is coded as 3120 and DOG is coded as 4157. How is BAT coded in the same scheme?', '["2120","2130","3120","2110"]'::jsonb, 0, 'aptitude', 'medium', true),
('In a certain code, each letter of MONEY is shifted 2 places forward in the alphabet (wrapping Z to B) to give OQPGA. Using the same code, how is SAVE written?', '["UCXG","UCXF","VCXG","UBXG"]'::jsonb, 0, 'aptitude', 'hard', true);
