name: Release PSGMX
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create .env.flutter
        working-directory: ./apps/mobile
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env.flutter
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env.flutter

      - name: Install Dependencies
        working-directory: ./apps/mobile
        run: flutter pub get

      - name: Build APK
        working-directory: ./apps/mobile
        run: flutter build apk --dart-define-from-file=.env.flutter --release --split-per-abi

      - name: Build Web
        working-directory: ./apps/mobile
        run: flutter build web --dart-define-from-file=.env.flutter --release

      - name: Zip Web Build
        working-directory: ./apps/mobile/build/web
        run: zip -r ../../../psgmx-web-build.zip ./*

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            apps/mobile/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            apps/mobile/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            apps/mobile/build/app/outputs/flutter-apk/app-x86_64-release.apk
            psgmx-web-build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
